<?php
session_start();
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

// Include the Composer autoloader to load PHPMailer classes
require 'vendor/autoload.php'; // This includes PHPMailer's autoload file, which is generated by Composer

// The allowed email address
$allowed_email = 'vinodbabukondapally@gmail.com';  // Replace this with the email you want to allow

if ($_SERVER["REQUEST_METHOD"] === "POST") {
    $email = $_POST['email'];

    // Check if the entered email matches the allowed email
    if ($email === $allowed_email) {
        // Generate a random 6-digit OTP
        $otp = rand(100000, 999999);

        // Store OTP in session to verify later
        $_SESSION['otp'] = $otp;
        $_SESSION['email'] = $email;

        // Setup PHPMailer
        $mail = new PHPMailer(true); 
        try {
            // Server settings
            $mail->isSMTP();                                            // Set mailer to use SMTP
            $mail->Host       = 'smtp.gmail.com';                        // Set the SMTP server to send through
            $mail->SMTPAuth   = true;                                    // Enable SMTP authentication
            $mail->Username   = 'vinodbabukondapally@gmail.com';                  // SMTP username (your email address)
            $mail->Password   = 'ymwp ifnm zbtz qyqr';                   // SMTP password (your email password)
            $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;          // Enable TLS encryption
            $mail->Port       = 587;                                     // TCP port to connect to

            // Recipients
            $mail->setFrom('vinodbabukondapally@gmail.com', 'Your Name');         // Sender's email
            $mail->addAddress($email);                                   // Add recipient's email

            // Content
            $mail->isHTML(true);                                          // Set email format to HTML
            $mail->Subject = 'Your OTP for Login';
            $mail->Body    = 'Your OTP is: ' . $otp;

            // Send email
            $mail->send();
            echo json_encode(["status" => "success", "message" => "OTP sent to your email."]);
        } catch (Exception $e) {
            echo json_encode(["status" => "error", "message" => "Message could not be sent. Mailer Error: {$mail->ErrorInfo}"]);
        }
    } else {
        echo json_encode(["status" => "error", "message" => "Invalid email. Only the allowed email can log in."]);
    }
}
?>
